### ISSUE TITLE
BTEUK-267-Progress-Mapper-On-Server-Editing

### ISSUE THREAD

**Issue by george112n** [BTEUK/Network#13]
Initial statement of the problem - We want a progress map for BTE UK that is editable by builders in the minecraft world. 

- Add a Progress Map Main Menu from which a player can see a list of nearby Progress Map features or an option to add a new feature.

- From this Menu player can click on a feature and this opens another Menu which allows the player to edit the properties and geometry of the feature

- Geometry of the feature can be edited in a way similar to world edit polygon selection

- The same menu design for editing a feature should be used for adding a feature

- Utilise ProgressMapperBackEnd to make the changes to the map

**Comment by LM-Wolfert** [comment]
Merged
